import {
  Armchair,
  Bike,
  Car,
  Dumbbell,
  Flower2,
  Glasses,
  Ham,
  Laptop,
  type LucideIcon,
  PaintBucket,
  ShoppingBag,
  Shirt,
  Smartphone,
  Sparkles,
  Tablet,
  Watch,
  Utensils,
} from 'lucide-react'

export const categoryIconMap: Record<string, LucideIcon> = {
  beauty: Sparkles,
  fragrances: Flower2,
  furniture: Armchair,
  groceries: Ham,
  'home-decoration': PaintBucket,
  'kitchen-accessories': Utensils,
  laptops: Laptop,
  'mens-shirts': Shirt,
  'mens-shoes': ShoppingBag,
  'mens-watches': Watch,
  'mobile-accessories': Smartphone,
  motorcycle: Bike,
  'skin-care': Sparkles,
  smartphones: Smartphone,
  'sports-accessories': Dumbbell,
  sunglasses: Glasses,
  tablets: Tablet,
  tops: Shirt,
  vehicle: Car,
  'womens-bags': ShoppingBag,
  'womens-dresses': Shirt,
  'womens-jewellery': Sparkles,
  'womens-shoes': ShoppingBag,
  'womens-watches': Watch,
}
